apiVersion: v1
kind: Service
metadata:
  name: demo-service
  namespace: demo
  labels:
    app: demo-app
spec:
  ports:
    - name: demo-ports
      nodePort: 31000
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: demo-app
  type: NodePort
