apiVersion: v1
kind: Service
metadata:
  name: simple-time
  labels:
    app.kubernetes.io/name: simple-time
    app.kubernetes.io/part-of: simple-time
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: simple-time
  ports:
    - name: http
      protocol: TCP
      port: 1117
      targetPort: 80
